# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studadmin', '0002_auto_20160814_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('promotion', models.IntegerField()),
                ('start_date', models.DateField()),
                ('the_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_promotion', to='studadmin.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('punishment', models.IntegerField()),
                ('start_date', models.DateField()),
                ('expity_time', models.DateField()),
                ('is_forgiven', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studadmin.Student')),
                ('the_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_violation', to='studadmin.Student')),
            ],
        ),
    ]
