# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studadmin', '0003_promotion_violation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='studadmin.Student')),
            ],
        ),
        migrations.AddField(
            model_name='promotion',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='studadmin.Student'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='the_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_promotion', to='studadmin.Staff'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='the_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_violation', to='studadmin.Staff'),
        ),
    ]
