# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studadmin', '0004_auto_20160814_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name', 'speciality']},
        ),
    ]
