# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studadmin', '0008_auto_20160814_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='habits',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='studadmin.Habits'),
        ),
    ]
