# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studadmin', '0010_auto_20160826_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habits',
            name='about',
        ),
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
