# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studadmin', '0011_auto_20160826_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='habits',
        ),
        migrations.AddField(
            model_name='student',
            name='habits',
            field=models.ManyToManyField(blank=True, default=None, to='studadmin.Habits'),
        ),
    ]
