# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studadmin', '0012_auto_20160826_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
