# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studadmin', '0014_auto_20160827_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
